[{
 nodeId:'apply',
 text:'申请',
 leaf:true,
 checked:false
},{
  nodeId:'approve',
  checked:false,
  leaf:true,
  text:'审核'
},{
	  nodeId:'countersign',
	  checked:false,
	  leaf:true,
	  text:'会签'
},{
  nodeId:'exaapprove',
  checked:false,
  leaf:true,

  text:'审批'
},{
	  nodeId:'exclusive',
	  checked:false,
	  leaf:true,
	  text:'判断前一节点'
},{
	  nodeId:'investigate',
	  checked:false,
	  leaf:true,
	  text:'审查'
}]